const endpoints = {
    apiLogin: '/api/user/login/',
    apiEmpresa: '/api/business/',
    apiEmpleado: '/api/employee/',
    apiSucursal: '/api/office/',
    apiKinship: '/api/kinship/',
    apiBenefi: '/api/benefi/',
    apiPlan: '/api/plan/',
    apiZona: '/api/zone/',
    apiDepartamento: '/api/department/',
    apiMunicipio: '/api/city/',
    apiFormaPago: '/api/paymentmethod/',
    apiContrato: '/api/contract/',
    apiMultifiltro: '/api/multifiltro/',
    apiBusqueda: '/api/search/',
    apiTipoPago: '/api/paymenttype/',
    apiPagos: '/api/payment/',
    apiCaja: '/api/cash/',
    apiEmpresas: '/api/empresas/',
    apiNoveltycontract: '/api/noveltycontract/',
    apiNovelty: '/api/novelty/',
    apiContractServicios: '/api/contractadicional/',
    apiServiceadicional: '/api/serviceadicional/',
}

export default endpoints;